import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConditionalLayout from "@/components/common/ConditionalLayout";
import { Toaster } from "@/components/ui/sonner";
import { ReduxProviders } from "@/Redux/ReduxProviders";
import { saveUserinMongoDB } from "@/lib/saveUserinMongoDB";
import NProgressProvider from "@/components/common/nprogressProvider";
import "./globals.css";
import { LoaderProvider } from "@/components/common/loaderProvider";
import AuthRedirectWrapper from "@/components/common/AuthRedirectWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  try {
    await saveUserinMongoDB();
  } catch (error) {
    console.error("Error in RootLayout:", error);
  }

  return (
    <ClerkProvider>
      <ReduxProviders>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <AuthRedirectWrapper>
              <ConditionalLayout>
                <LoaderProvider>
                  <NProgressProvider>
                    {children}
                    <Toaster />
                  </NProgressProvider>
                </LoaderProvider>
              </ConditionalLayout>
            </AuthRedirectWrapper>
          </body>
        </html>
      </ReduxProviders>
    </ClerkProvider>
  );
}
